import { FaCaretRight } from "react-icons/fa";

export const aboutMainItemMobile = [
  {
    id: 1,
    title: "Company",
    companyData: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Our company",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "How we work",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Core team",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Agile development",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Career",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Full cycle product development",
        service: [
          {
            id: 1,
            image: <FaCaretRight />,
            href: "/",
            title: "Product management",
          },
          {
            id: 2,
            image: <FaCaretRight />,
            href: "/",
            title: "MVP",
          },
          {
            id: 3,
            image: <FaCaretRight />,
            href: "/",
            title: "Startups",
          },
          {
            id: 4,
            image: <FaCaretRight />,
            href: "/",
            title: "Enterprise",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Project Costing",
    projectCosting: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Proof of Concept (PoC)",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "System Audit",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Software Maintenance",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Minimum Viable Product (MVP)",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Product Discovery",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IT Consulting",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Digital Marketing Services",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Consulting Services",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Server Support",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DevOps",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "UX/UI design",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "QA and testing",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "R&D services",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Software support and maintenance",
      },
    ],
  },
  {
    id: 3,
    title: "Dedicated resources",
    dedicatedResources: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "GA3 to GA4 Migration",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Advanced GA & GTM Set-up Services",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "SEO Services",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Local SEO Services",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Ecommerce SEO Services",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "PPC Marketing",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Amazon Marketing Services",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Social Media Marketing",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Display Media Marketing",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Influencer Marketing",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Branding & Identity Marketing",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Mobile Marketing",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Content Marketing",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Lead Generation Services",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Email Marketing",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Remarketing Services",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Online Reputation Management (ORM)",
      },
    ],
  },
  {
    id: 4,
    title: "City we work in",
    cityWeWorkIn: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "New York",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Paris",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Beijing",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Mexico City",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "São Paulo",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Hong Kong",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Vienna",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Dubai",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Prague",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Toronto",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Osaka",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "London",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Guangzhou",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Lisbon",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Hangzhou",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Tokyo",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Amsterdam",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Sydney",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Dhaka",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Barcelona",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Istanbul",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Madrid",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cape Town",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Seoul",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Chicago",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Los Angeles",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Rio de Janeiro",
      },
    ],
  },
];
