export const blockchainMainItemMobile = [
  {
    id: 1,
    title: "NFTs",
    nfts: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-development-services",
        title: "NFT Development Services",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/white-label-nft-marketplace-development-company",
        title: "White-Label NFT Marketplace",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Development",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/free-nft-consulting-services",
        title: "Free NFT Consulting",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Ecosystem",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/white-label-multi-chain-nft-marketplace-development-company",
        title: "Whitelabel Multi chain NFT",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/white-label-nft-launchpad-development-company",
        title: "White Label NFT Launchpad",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-launchpad-development-company",
        title: "NFT Launchpad Development",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/cross-chain-nft-marketplace-development-company",
        title: "Cross-Chain NFT Marketplace",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-exchange-development-company",
        title: "NFT Exchange Development",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-wallet-development-services",
        title: "NFT Wallet Development",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-minting-platform-development-services",
        title: "NFT Minting Platform Development",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/non-fungible-token-development-services",
        title: "NFT Token Development",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/dao-enabled-nft-platform-development-services",
        title: "DAO Enabled NFT Platform",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-marketplace-with-governance-token-development-services",
        title: "NFT marketplace with Governance",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/celebrity-nft-marketplace-development-services",
        title: "Celebrity NFT Marketplace",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/music-nft-marketplace-development-company",
        title: "NFT Marketplace for Music",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nfts-marketplace-for-artist",
        title: "NFT Marketplace for Artist",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/sports-nft-marketplace-development-services",
        title: "NFT Marketplace For Sports",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace for Real estate",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-physical-assets-marketplace-development-company",
        title: "NFT for Physical assets",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT in E-commerce",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        href: "/nfts/nft-ticketing-marketplace-development-services",
        title: "NFT Ticketing Marketplace",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "SFT Development",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Studio",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Aggregator Marketplace",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace On Ethereum",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace On Matic",
      },
      {
        id: 29,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace on BSC",
      },
      {
        id: 30,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace On Astar",
      },
      {
        id: 31,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace on Avalanche",
      },
      {
        id: 32,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Development On Sidechain",
      },
      {
        id: 33,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace On Solana",
      },
      {
        id: 34,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Zksync2.0 Integration Service",
      },
      {
        id: 35,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace On Harmony",
      },
      {
        id: 36,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Like SuperRare",
      },
      {
        id: 37,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace like Sudoswap",
      },
      {
        id: 38,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Like Sorare",
      },
      {
        id: 39,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Like OpenSea",
      },
      {
        id: 40,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace like Solsea",
      },
      {
        id: 41,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Like Rarible",
      },
      {
        id: 42,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Like NBA Top Shot",
      },
      {
        id: 43,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Layer 2 Development",
      },
      {
        id: 44,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Phygital NFT Marketplace",
      },
      {
        id: 45,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Carbon Credits Development",
      },
      {
        id: 46,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "P2E NFT Game Development",
      },
      {
        id: 47,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "White Label P2E NFT Games",
      },
      {
        id: 48,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web2 to Web3 Game",
      },
      {
        id: 49,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Game Marketplace",
      },
      {
        id: 50,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Move To Earn NFT Platform",
      },
      {
        id: 51,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Gaming Platform",
      },
      {
        id: 52,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Splinterlands Like NFT Game",
      },
      {
        id: 53,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Dungeon Swap Like NFT Game",
      },
      {
        id: 54,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "My Crypto Heros Like NFT Game",
      },
      {
        id: 55,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Zed Run Like NFT Game",
      },
      {
        id: 56,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Decentraland Like NFT Game",
      },
      {
        id: 57,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Racing Game",
      },
      {
        id: 58,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Revv Racing Like NFT Game",
      },
      {
        id: 59,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Casino Game",
      },
      {
        id: 60,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT RPG Game Development",
      },
      {
        id: 61,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Social Token Development",
      },
      {
        id: 62,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Staking platform",
      },
      {
        id: 63,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Streaming Platform",
      },
      {
        id: 64,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Consulting Service",
      },
      {
        id: 65,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Listing Services",
      },
      {
        id: 66,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Fractional NFT Marketplace",
      },
      {
        id: 67,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Shards NFT Platform",
      },
    ],
  },
  {
    id: 2,
    title: "Marketing",
    marketing: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketing Services",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Marketplace Marketing Services",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Collectibles Marketing",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Game Marketing",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Telegram Marketing",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Influencer Marketing Agency",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT PR/Media Marketing",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "NFT Discord Marketing",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Discord Marketing",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Discord Server Marketing",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Discord Brand Marketing",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Discord Game Marketing",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DeFi Marketing Services",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Exchange Marketing",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web 3.0 Marketing Services",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Marketing",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Community Marketing",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Telegram Marketing",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Influencer Marketing",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Youtube Influencer",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "STO Marketing",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Marketing",
      },
    ],
  },
  {
    id: 3,
    title: "Metaverse",
    metaverse: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-development-company",
        title: "Metaverse Development Services",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-nft-marketplace-development-company",
        title: "Metaverse NFT Marketplace Development",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-healthcare-solutions-development-company",
        title: "Metaverse Healthcare Solutions",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/nft-metaverse-launchpad-development-company",
        title: "NFT Metaverse Launchpad Development",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-nft-game-development-company",
        title: "Metaverse NFT Game Development",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-art-gallery-development-company",
        title: "Metaverse Art Gallery",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-avtar-development-company",
        title: "Metaverse Avatar Development",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-3d-space-development-company",
        title: "Metaverse 3D Space Development",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-event-platform-development-company",
        title: "Metaverse Event Platform",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-platform-for-social-interaction-development-company",
        title: "Metaverse Platform for Social Interaction",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/metaverse/metaverse-virtual-working-space-development-company",
        title: "Metaverse Virtual Working Space",
      }
    ],
  },
  {
    id: 4,
    title: "Web 3.0",
    web3: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web 3.0 Development",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web3 dApp Development",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web3 Wallet Development",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web 3.0 Game Development",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web 3.0 Marketing Services",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Metamask like Wallet Development",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web 3.0 Development",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Web 3.0 Development",
      },
    ],
  },
  {
    id: 5,
    title: "DeFi",
    defi: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-development-services",
        title: "Decentralized Finance (DeFi) Development",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-pancakeswap-services-development-company",
        title: "DeFi Platform like Pancakeswap",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/dao-development-services",
        title: "DAO Services",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/white-label-Swap-exchange-development-services",
        title: "Whitelabel Swap Exchange Development",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Pinksale Like Launchpad Development",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-staking-platform-development-company",
        title: "DeFi Staking Platform Development",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-yield-farming-development-services",
        title: "DeFi Yield Farming Development",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-marketing-services-company",
        title: "DeFi Marketing Services",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DeFi Application Development Services",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-token-development-services",
        title: "DeFi Token Development Services",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-wallet-development-services",
        title: "DeFi Wallet Development Solution",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-synthetic-assets-development-services",
        title: "DeFi Synthetic Assets Development",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-tokenization-development-company",
        title: "DeFi Tokenization Development",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-crowd-funding-platform-development-company",
        title: "DeFi crowdfunding platform",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-real-estate-platform-development-company",
        title: "DeFi Real estate platform",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-dex-development-services",
        title: "DeFi Exchange Development Solution",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-swap-development-like-uniswap-services",
        title: "DeFi Platform Like Uniswap",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/defi/defi-protocol-development-like-yearn-finance-services",
        title: "DeFi Protocol Development like yearn finance",
      }
    ],
  },
  {
    id: 6,
    title: "ICO/STO/IDO",
    icoStoIdo: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Development",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Marketing",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Community Marketing",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Telegram Marketing",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ICO Influencer Marketing",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IEO Development",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ETO Development",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Crowdfunding Platform",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "STO Development",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "STO Marketing",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "STO Smart Contracts",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Real Estate Tokenization",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Asset Tokenization",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Art Tokenization",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Tokenization Platform",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Development",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Marketing",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "White Label IDO Launchpad",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Token Launchpad",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Launchpad On BSC",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Launchpad On Ethereum",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Launchpad In Multichain",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IDO Launchpad On Polygon",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IGO Launchpad Development",
      },
    ],
  },
  {
    id: 7,
    title: "Crypto",
    crypto: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Development",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Stable Coin Development",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "White label Crypto Exchange",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Exchange Development",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Decentralized Exchange Development",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "P2P Exchange Development",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Wallet Development",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Crypto-Payment Development",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Exchange Listing Services",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Exchange Like Wazirx",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Exchange Like Binance",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Exchange Like Coinbase",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cryptocurrency Exchange Like Binance",
      },
    ],
  },
  {
    id: 8,
    title: "Blockchain",
    blockchain: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/blockchain/blockchain-development-services",
        title: "Blockchain Development",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/blockchain/white-lable-blockchain-development-services",
        title: "White Label Blockchain Solutions",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/blockchain/custom-blockchain-development-on-avalanche",
        title: "Custom Blockchain On Avalanche",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/blockchain/custom-blockchain-development-on-polygon",
        title: "Custom Blockchain On Polygon",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/blockchain/blockchain-game-development-services",
        title: "Blockchain Game Development",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/blockchain/blockchain-game-development-services",
        title: "Solana Blockchain Development",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Blockchain / Web3.0 Consulting",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Proof Of Reserve",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Defi Platform like Synthetix",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Carbon Credits Development",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Blockchain for Finance",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Blockchain for Pharma Industry",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Protocol Implementation",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "EVM Compatible Blockchain and Service",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Smart Contract Development",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DApps Development",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "P2P Lending Software",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Blockchain for Finance",
      },
    ]
  },
];
