export const gamesMainItemMobile = [
  {
    id: 1,
    title: "Game Development",
    gameDevelopment: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Android Game Development",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "iOS Game Development",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Mmorpg Game Development",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Game Development",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Game Testing",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Game Porting",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Unity Development",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Unreal Development",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "PC Game Development",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Mobile Game Development",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hyper Casual Game Development",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "C++ Game Development",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Gamification Services",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "NFT Game Development",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "NFT Marketplace Development",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Metaverse Development",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "Blockchin Game Development",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "Play-To-Earn Game Development",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "NFT Desing Company",
        href: "/",
      },
    ],
  },
  {
    id: 2,
    title: "Game Art",
    gameArt: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Concept Art",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Casual Art",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Environment Design",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Character Design",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Character Design",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "AAA",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "2D Art",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Slots Games Art",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "2D Characters Design",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "2D Environment Design",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Art",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hidden Objects",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Game Level Design",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "Game Economy Design",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Charaters Design",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Environment Design",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Game Modeling",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Sculpting",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "UI/UX Design",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "Illustration Services",
        href: "/",
      },
    ],
  },
  {
    id: 3,
    title: "Animation",
    animation: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "2D Animation",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Animation",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Motion Graphic Animation",
        href: "/",
      },
    ],
  },
  {
    id: 4,
    title: "Outstaffing",
    outstaffing: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Game Developers",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Unity Developers",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Unreal Developers",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire 3D Artists",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire 3d Modelers",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Game Designers",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Game Designers",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Character Designers",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Concept Artists",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire 2D Artists",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire Illustrators",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire 2D Animators",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hire 3D Animators",
        href: "/",
      },
    ],
  },
];
