export const industriesMainItemMobile = [
  {
    id: 1,
    title: "Education",
    education: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Authoring Systems",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Assessment Software",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Drill & Practics Software",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Desktop Publishing",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Special Needs Software",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Wath Problem Solving Software",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Utility Software",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Graphic Software",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tutorial Software",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Reference Software",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Educational Games",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Simulations",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Courseware",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "Math Problem Solving Software",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "Simulations",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Modelling",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "Educational Robotics & MBL",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "Programmable Systems",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "Virtual Reality Applications",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hypermedia",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "Drill and Practice",
        href: "/",
      },

      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "Collaborative Distance Learning Systems",
        href: "/",
      },
    ],
  },
  {
    id: 2,
    title: "Banking & Finance",
    bankingFinance: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Core Banking",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Corporate Banking",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Credits and Loans",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Fraud Management",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Investments",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Marketing Activities",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Operational Intelligence",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Regional and Local Support",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Risk Management",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Wealth Management",
        href: "/",
      },
    ],
  },
  {
    id: 3,
    title: "Ecommerce",
    ecommerce: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Authoring Systems",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Assessment Software",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Drill & Practics Software",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Desktop Publishing",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Special Needs Software",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "3D Animation",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Motion Graphic Animation",
        href: "/",
      },
    ],
  },
  {
    id: 4,
    title: "Gaming",
    gaming: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Unreal Engine",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Unity",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Metal",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Amazon Lumberyard",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Blender",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Construct 3",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "GameMaker",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "CRYENGINE",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Godot Engine",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Maya LT",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Gamefroot",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "GDevelop",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "GameSalad",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "Buildbox",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "DeltaEngine",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Panda3D",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "Superpowers",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "RPG Maker VX Ace",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "Cocos2d-x",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "Corona",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "Clickteam Fusion",
        href: "/",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "MonoGame",
        href: "/",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        title: "NeoAxis Engine",
        href: "/",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        title: "Photon",
        href: "/",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        title: "Helix Core",
        href: "/",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        title: "Leadwerks",
        href: "/",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        title: "SpriteKit",
        href: "/",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        title: "Arcweave",
        href: "/",
      },
      {
        id: 29,
        image: "/assets/Header/About/Our-company.svg",
        title: "Stencyl",
        href: "/",
      },
      {
        id: 30,
        image: "/assets/Header/About/Our-company.svg",
        title: "Defold",
        href: "/",
      },
      {
        id: 31,
        image: "/assets/Header/About/Our-company.svg",
        title: "Starling",
        href: "/",
      },
      {
        id: 32,
        image: "/assets/Header/About/Our-company.svg",
        title: "Haxe",
        href: "/",
      },
      {
        id: 33,
        image: "/assets/Header/About/Our-company.svg",
        title: "GamePlay3D",
        href: "/",
      },
    ],
  },
  {
    id: 5,
    title: "Food & Restaurant",
    foodRestaurant: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Point-of-sale systems",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Accounting software",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Loyalty programs",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Third-party delivery apps",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Employee training applications",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Scheduling software",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Payroll programs",
        href: "/",
      },
    ],
  },
  {
    id: 6,
    title: "Texi Booking",
    texiBooking: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Onde",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Cabsoluit",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "AllRide",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "SpotnRides",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "SmartCar",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Infinite Cab",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Cab Treasure",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Cabookie",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Taxi Mobile Solutions",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Limo n' Taxi",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "CabbyGo",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "M-DATS",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "TaxiCaller",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "RideBits",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "Mtoag Taxi App",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "ESuper",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "TaxiTapp",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "Taxi On The Go",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "Sherlock Taxi Solution",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "FareBookings.com",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "Dispatching Made Easy",
        href: "/",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "Cordic",
        href: "/",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        title: "Taxi Billing & Management Software",
        href: "/",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        title: "YelowTaxi",
        href: "/",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        title: "PerGo Dispatch",
        href: "/",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        title: "Call Taxi Management System",
        href: "/",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        title: "Eber",
        href: "/",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        title: "TaxiMobility",
        href: "/",
      },
      {
        id: 29,
        image: "/assets/Header/About/Our-company.svg",
        title: "Taxi Pulse",
        href: "/",
      },
      {
        id: 30,
        image: "/assets/Header/About/Our-company.svg",
        title: "UnicoTaxi",
        href: "/",
      },
      {
        id: 31,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tagmytaxi",
        href: "/",
      },
      {
        id: 32,
        image: "/assets/Header/About/Our-company.svg",
        title: "CabStartup",
        href: "/",
      },
      {
        id: 33,
        image: "/assets/Header/About/Our-company.svg",
        title: "Voila Cabs",
        href: "/",
      },
      {
        id: 34,
        image: "/assets/Header/About/Our-company.svg",
        title: "Karry",
        href: "/",
      },
      {
        id: 35,
        image: "/assets/Header/About/Our-company.svg",
        title: "BooknRide",
        href: "/",
      },
    ],
  },
  {
    id: 7,
    title: "Dating",
    dating: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Bumble: Dating & Friends app",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tinder: Dating app. Meet. Chat",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hinge Dating App: Meet People",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Badoo - Dating. Chat. Meet.",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Dating and Chat - SweetMeet",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hily: Dating app. Meet People. ",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Chispa: Dating App for Latinos",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Dating with singles - iHappy",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "BLK Dating: Meet Black Singles",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Dating and Chat - Evermatch",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Match Dating: Chat, Date, Meet",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "OkCupid - Dating App",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Zoosk - Social Dating App",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "Dating and chat - Maybe You",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "Match Dating: Chat, Date, Meet",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "OkCupid - Dating App",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "YouFlirt - flirt & chat app",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "3Fun: Threesome Couples Dating",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "Seeking",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "Turn Up - Match through music!",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "Magnet: Meet & Chat Dating App",
        href: "/",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "Ukaku - Live video chat",
        href: "/",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        title: "InterracialCupid: Mixed Dating",
        href: "/",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        title: "AsianDating: Asian Dating",
        href: "/",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        title: "Mingle2: Dating, Chat & Meet",
        href: "/",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        title: "Global Video call Random Cally",
        href: "/",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        title: "Threesome Swingers App - 3way",
        href: "/",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        title: "Wild: Hook up, Meet, Dating Me",
        href: "/",
      },
    ],
  },
  {
    id: 8,
    title: "Travel & Transport",
    travelTransport: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "TripActions",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "TravelPerk",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "iGMS",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "SWITCH.CM",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hosthub",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Bookster",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hostaway",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tourwriter",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "NexTravel",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tourdesk",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Roundme",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Bookeo",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "NextBillion.ai",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "YouLi",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "TravelPerk",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Minim",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "ITILITE",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "Routespring",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "TravelPerk",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "FunAway",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "FunAway",
        href: "/",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "Properly",
        href: "/",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        title: "BookingSync",
        href: "/",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        title: "Rentals United",
        href: "/",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hostfully",
        href: "/",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tokeet",
        href: "/",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        title: "Locomote",
        href: "/",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        title: "Ezus",
        href: "/",
      },
      {
        id: 29,
        image: "/assets/Header/About/Our-company.svg",
        title: "bookingkit",
        href: "/",
      },
      {
        id: 30,
        image: "/assets/Header/About/Our-company.svg",
        title: "Quicktext",
        href: "/",
      },
      {
        id: 31,
        image: "/assets/Header/About/Our-company.svg",
        title: "MiX Telematics",
        href: "/",
      },
      {
        id: 32,
        image: "/assets/Header/About/Our-company.svg",
        title: "PHPTRAVELS",
        href: "/",
      },
      {
        id: 33,
        image: "/assets/Header/About/Our-company.svg",
        title: "Transporters.io",
        href: "/",
      },
      {
        id: 34,
        image: "/assets/Header/About/Our-company.svg",
        title: "Advensure",
        href: "/",
      },
    ],
  },
  {
    id: 9,
    title: "Events & Tickets",
    eventsTickets: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Cvent",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Webex Events (formerly Socio)",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hubilo",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Whova",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "vFairs",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Eventbrite",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Airmeet",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hopin",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Bizzabo",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tourdesk",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "BigMarker",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Swoogo",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Splash",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "GoTo Webinar",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "PheedLoop",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Swapcard",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "EventX",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "Zuddl",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "EventMobi",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "Airmeet",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "6Connex",
        href: "/",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "Goldcast",
        href: "/",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        title: "Bevy",
        href: "/",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        title: "Blackthorn Events",
        href: "/",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        title: "Odoo Events",
        href: "/",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        title: "Accelevents",
        href: "/",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        title: "AnyRoad",
        href: "/",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        title: "Canapii",
        href: "/",
      },
      {
        id: 29,
        image: "/assets/Header/About/Our-company.svg",
        title: "FLOOR by 10Times",
        href: "/",
      },
      {
        id: 30,
        image: "/assets/Header/About/Our-company.svg",
        title: "Glue Up",
        href: "/",
      },
      {
        id: 31,
        image: "/assets/Header/About/Our-company.svg",
        title: "EventCreate",
        href: "/",
      },
      {
        id: 32,
        image: "/assets/Header/About/Our-company.svg",
        title: "ON24",
        href: "/",
      },
      {
        id: 33,
        image: "/assets/Header/About/Our-company.svg",
        title: "Localist",
        href: "/",
      },
      {
        id: 34,
        image: "/assets/Header/About/Our-company.svg",
        title: "Sched",
        href: "/",
      },
      {
        id: 35,
        image: "/assets/Header/About/Our-company.svg",
        title: "AudienceView Professional",
        href: "/",
      },
      {
        id: 36,
        image: "/assets/Header/About/Our-company.svg",
        title: "Explara Event Management Cloud",
        href: "/",
      },
      {
        id: 37,
        image: "/assets/Header/About/Our-company.svg",
        title: "InEvent",
        href: "/",
      },
      {
        id: 38,
        image: "/assets/Header/About/Our-company.svg",
        title: "Joyn",
        href: "/",
      },
      {
        id: 39,
        image: "/assets/Header/About/Our-company.svg",
        title: "Eventene",
        href: "/",
      },
    ],
  },
  {
    id: 10,
    title: "Social Networking",
    socialNetworking: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Tribe",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Zoho Connect",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Flock",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Yammer",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "eXo Platform",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "SocialEngine",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Whaller",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "HumHub",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Disciple",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Open Source Social Network",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "SocialBuddy",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Bitrix24",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "ConferenceNet",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "Crea8socialPRO",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "SkaDate",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Elgg",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "BuddyPress",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "Oxwall",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "Jcow",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "friendica",
        href: "/",
      },
    ],
  },
  {
    id: 11,
    title: "On Demand",
    onDemand: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Consumer goods",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Crowdfunding",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Education",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Recruiting",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "Delivery",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Food",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Transportation",
        href: "/",
      },
    ],
  },
  {
    id: 12,
    title: "Healthcare & Fitness",
    healthcareFitness: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        title: "Electronic Health Records Software",
        href: "/",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        title: "Telemedicine Software",
        href: "/",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        title: "Health Tracking Apps",
        href: "/",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hospital Management Software",
        href: "/",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        title: "e-Prescribing Software",
        href: "/",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        title: "Remote Patient Monitoring Software",
        href: "/",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        title: "Medical Diagnosis Software",
        href: "/",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        title: "Healthcare Billing Software",
        href: "/",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        title: "Medical Image Analysis Software",
        href: "/",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        title: "Personal Health Record Software",
        href: "/",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        title: "Over to You",
        href: "/",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        title: "Digital transformation in healthcare",
        href: "/",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        title: "Electronic Health Records (EHR)",
        href: "/",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        title: "Telemedicine software",
        href: "/",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        title: "Remote Patient Monitoring (RPM)",
        href: "/",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        title: "Hospital Management Systems (HMS)",
        href: "/",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        title: "Healthcare CRM Software",
        href: "/",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        title: "E-prescriptions software",
        href: "/",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        title: "Medical diagnosis software",
        href: "/",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        title: "Appointment booking software",
        href: "/",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        title: "Health tracking apps",
        href: "/",
      },
      {
        id: 22,
        image: "/assets/Header/About/Our-company.svg",
        title: "Medical billing software",
        href: "/",
      },
      {
        id: 23,
        image: "/assets/Header/About/Our-company.svg",
        title: "Clinical trial management software",
        href: "/",
      },
      {
        id: 24,
        image: "/assets/Header/About/Our-company.svg",
        title: "Mobile health (mHealth) apps",
        href: "/",
      },
      {
        id: 25,
        image: "/assets/Header/About/Our-company.svg",
        title: "Remote medical training",
        href: "/",
      },
      {
        id: 26,
        image: "/assets/Header/About/Our-company.svg",
        title: "Medical imaging",
        href: "/",
      },
      {
        id: 27,
        image: "/assets/Header/About/Our-company.svg",
        title: "Personal health record software",
        href: "/",
      },
      {
        id: 28,
        image: "/assets/Header/About/Our-company.svg",
        title: "Medical research software",
        href: "/",
      },
      {
        id: 29,
        image: "/assets/Header/About/Our-company.svg",
        title: "Clinical trial management software",
        href: "/",
      },
    ],
  },
];
