export const technologiesMainItemMobile = [
  {
    id: 1,
    title: "Bi & Analytics",
    biAnalytics: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Power BI",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Tableau",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Big Data",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Pentaho BI",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Predictive Analytics",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Datapine",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Sisense",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Yellowfin BI",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Qlikview",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "SAP BI",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "SAP BI",
      },
    ],
  },
  {
    id: 2,
    title: "Cloud",
    cloud: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Azure",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AWS",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Salesforce",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Google cloud",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Oracle Cloud",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Microsoft Azure",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DigitalOcean",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "VMware",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IBM",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Citrix Systems",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Microsoft Corporation",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cisco",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "BMC Software",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "ServerSpace",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Kamatera",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Rackspace",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Red Hat",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "SAP",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Verizon Cloud",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Navisite",
      },
      {
        id: 21,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Dropbox",
      },
    ],
  },
  {
    id: 3,
    title: "Mobile",
    mobile: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "React Native",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Flutter",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IOS",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Swift",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Kotlin",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Android",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "React Native",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "React Native",
      },
    ],
  },
  {
    id: 4,
    title: "Frontend",
    frontend: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "React",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Angular",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "JavaScript",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Vue",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Vue",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Vue",
      },
    ],
  },
  {
    id: 5,
    title: "Backend",
    backend: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Laravel",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Node",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: ".NET",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Python",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Java",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Java",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Python",
      },
    ],
  },
  {
    id: 6,
    title: "Trending Tech",
    trendingTech: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "IoT",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Machine Learning",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Artificial Intelligence",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "MEAN Stack",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DevOps",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "DevOps",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "MEAN Stack",
      },
    ],
  },
  {
    id: 7,
    title: "AI",
    ai: [
      {
        id: 1,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Natural Language Generation",
      },
      {
        id: 2,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Speech Recognition",
      },
      {
        id: 3,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Machine Learning Platforms",
      },
      {
        id: 4,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Virtual Agents",
      },
      {
        id: 5,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Decision Management",
      },
      {
        id: 6,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Optimized Hardware",
      },
      {
        id: 7,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Deep Learning Platforms",
      },
      {
        id: 8,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Biometrics",
      },
      {
        id: 9,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Robotic Process Automation",
      },
      {
        id: 10,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Text Analytics And NLP",
      },
      {
        id: 11,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Cyber Defence",
      },
      {
        id: 12,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Content Creation",
      },
      {
        id: 13,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Emotion Recognition",
      },
      {
        id: 14,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "Marketing Automation",
      },
      {
        id: 15,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Application in E-Commerce",
      },
      {
        id: 16,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Application in Education",
      },
      {
        id: 17,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Application in Lifestyle",
      },
      {
        id: 18,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Application inNavigation",
      },
      {
        id: 19,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Application inHealthcare",
      },
      {
        id: 20,
        image: "/assets/Header/About/Our-company.svg",
        href: "/",
        title: "AI Application in Agriculture",
      },
    ],
  },
];
